backend:
  name: git-gateway
  branch: master

media_folder: src/images
public_folder: /img

collections:
  - name: 'projects'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Project url', name: 'slug', widget: 'string' }
      - { label: 'Project title', name: 'project-title', widget: 'string' }
      - { label: 'Project category', name: 'project-category', widget: 'string' }
      - { label: 'Project description', name: 'project-description', widget: 'string' }
      - { label: 'Article body', name: 'article', widget: 'markdown' }
