backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: content/projects/images
public_folder: /images

collections:
  - name: 'projects'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'URL', name: 'slug', widget: 'string' }
      - { label: 'Cover image', name: 'image', widget: 'file' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Article body', name: 'body', widget: 'markdown' }
